version: "3.9"
services:
    db:
        image: postgres:latest
        container_name: postgresql
        volumes:
            - tutorial-volume:/app/postgresql/data
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=chatbot
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=congminh
        networks:
            - djangonetwork
    backend:    
        build: ./backend
        container_name: django_backend
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"
        volumes:
            - ./backend:/app/backend
        environment:
            - DB_HOST=db
            - DB_USER=postgres
            - DB_PASS=congminh
            - DB_NAME=chatbot
        ports:
            - "8000:8000"
        networks:
            - djangonetwork
        depends_on:
            - db
    frontend:
        build: ./frontend
        container_name: react_frontend
        volumes:
            - ./frontend:/app/frontend
            - /app/frontend/node_modules
        ports:
            - "3000:3000"
        command: ["npm", "start"]
        depends_on:
            - backend
volumes:
    tutorial-volume:
networks:
    djangonetwork:
        driver: bridge
    
    
