server:
  ip_address: "0.0.0.0"
  port: 8000

mongodb:
  link_db_server: "mongodb+srv://cminh_chatbot:231196168@covidcluster.lxgvr.mongodb.net/test"
create_chatbot_api:
  general_chatbot:
    spell_corection:
      short_word_file: "data/spell_corection/short_word.json"
      teencode_regex: "data/spell_corection/teencode_regex.json"
      single_word_dic: "data/spell_corection/unidecode_vietnamese_dic.txt"
      eng_file: "data/spell_corection/eng_dic.json"
      vowel: "data/spell_corection/vietnamese_vowel.json"
      telex_fault: "data/spell_corection/additional_telex_fault.json"
      tudien_don: "data/spell_corection/tudien_don.json"

models_chatbot:
  response_data: "models/response.json"
  response_knn: "models/data_knn.json"
  emergency_contact: "data/emergycontact/contact.json"
  model_load_text:
    intent_model:  "models/intent_svm.pickle"
    model: "models/sub_svm.pickle"
    knn_model: "models/knn.pickle"
log:
  app: "app.log"
  request: "request.log"