FROM python:3.8

WORKDIR /app
COPY setup.py .
RUN pip install -e .

WORKDIR /app/backend
COPY requirements.txt /app/backend
RUN pip install -r requirements.txt

EXPOSE 8000
CMD ["sh","-c","cd backend&&python app.py"]