module.exports = {
    hello: "Xin chào, mình là Covid Chatbot. Bạn cần mình tư vấn gì hong",
    err: "Có lỗi xảy ra, bạn vui lòng F5 lại trang giúp mình nhé!",
    cantfind: "Không tìm được thủ tục thỏa các yêu cầu, hãy nhập chính xác yêu cầu tên thủ tục",
    thank: "Cảm ơn bạn. Chúc bạn có một ngày vui vẻ!",
    whatyourattr: "Yêu cầu của bạn là gì?",
    showall: "Bạn có muốn xem thêm kết quả không?",
    dontunderstand: "Mình không hiểu ý của bạn lắm. Xin hãy nhập lại.",
    reset: 'Hãy nhập thông tin bạn cần nhé',
    diadiem: ['Làm thủ tục này tại:','Bạn có thể đến'],
    nochiphi: 'Thủ tục này không cần chi phí nào',
    chiphi: ['Thủ tục này gồm các lệ phí sau: ','Bạn cần chuẩn bị lệ phí cho: '],
    thoigian: 'Thời gian làm thủ tục này là: ',
    True: 'True',
    False: 'False',
    rep_hello: "Hello bạn ạ",
    rep_done: "Cảm ơn bạn.",
}